
pipeline {
    agent any

    environment {
        IMAGE_NAME = "python_app"
        IMAGE_TAG = "${BUILD_NUMBER}"
        CONTAINER_NAME = "python_app_container"
    }

    stages {
        stage('Build') {
            steps {
                echo 'Building Docker image...'
                sh 'docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .'
            }
        }

        stage('Test') {
            steps {
                echo 'Running tests...'
                sh 'docker run --rm ${IMAGE_NAME}:${IAMGE_TAG} pytest'
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying application...'
                sh '''
                    docker stop ${python_app_container} || true
                    docker rm ${python_app_container} || true
                    docker run -d -p 8080:8080 --name ${python_app_container} ${IMAGE_NAME}:${IMAGE_TAG}
                '''
            }
        }
    }

    post {
        always {
            echo 'Pipeline completed.'
        }
    }
}

